---
title: "Topic"
author: '110078509'
date: '2022'
output:
  html_document: default
  pdf_document: default
  word_document: default
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE) 
rm(list=ls()) 
library(tidyverse) 
library(ggplot2) 

#remove the random variable to fresh the working environment 
```

```{r}

```

------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------


#### 

##### 

```{r}

```

#### 

```{r}

```

----------------------------------

#### 


#### 

#####

```{r}

```

#####  

----------------------------------

#####  


```{r}


```

*Ans:*



----------------------------------

#### 

```{r}

```
*Ans:* 


----------------------------------

#### 

*Ans:*


----------------------------------

##### 

*Ans:*



------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------


#### 
```{r}

```
----------------------------------

##### 

```{r}

```
----------------------------------

##### 


```{r}

```

*Ans*: 



----------------------------------

##### 



```{r}

```
*Ans: * 



----------------------------------

#####

```{r}

```
*Explain:*




------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------

#####

*Ans. *

```{r}

```



```{r}

```


```{r}


```



```{r}

```



