% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={HW4},
  pdfauthor={110078509},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{HW4}
\author{110078509}
\date{20220309}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list=}\FunctionTok{ls}\NormalTok{()) }
\CommentTok{\#remove the random variable to fresh the working environment}
\end{Highlighting}
\end{Shaded}

\hypertarget{q1.-given-the-critical-doi-score-that-google-uses-to-detect-malicious-apps}{%
\subsection{Q1. Given the critical DOI score that Google uses to detect
malicious
apps}\label{q1.-given-the-critical-doi-score-that-google-uses-to-detect-malicious-apps}}

\hypertarget{a}{%
\subsubsection{(a)}\label{a}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{3.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0001077997
\end{verbatim}

\hypertarget{b}{%
\subsubsection{(b)}\label{b}}

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{2.2}\SpecialCharTok{*}\DecValTok{1000000}\SpecialCharTok{*}\FunctionTok{pnorm}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{3.7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 237.1594
\end{verbatim}

\hypertarget{question-2}{%
\subsection{Question 2)}\label{question-2}}

\#\#a. The Null distribution of t-values:

\hypertarget{i.-visualize-the-distribution-of-verizons-repair-times-marking-the-mean-with-a-vertical-line}{%
\subsubsection{i. Visualize the distribution of Verizon's repair times,
marking the mean with a vertical
line}\label{i.-visualize-the-distribution-of-verizons-repair-times-marking-the-mean-with-a-vertical-line}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{raw }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"verizon.csv"}\NormalTok{, }\AttributeTok{header =}\NormalTok{ T)}\SpecialCharTok{$}\NormalTok{Time}

\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(raw), }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{, }
     \AttributeTok{main=}\StringTok{"distribution of Verizon’s repair times"}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\FunctionTok{mean}\NormalTok{(raw), }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW4_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{ii.-given-what-puc-wishes-to-test-how-would-you-write-the-hypothesis-not-graded}{%
\subsubsection{ii. Given what PUC wishes to test, how would you write
the hypothesis? (not
graded)}\label{ii.-given-what-puc-wishes-to-test-how-would-you-write-the-hypothesis-not-graded}}

PUC wants to test whether Verizontake average 7.6 minutes to repair
phone services for its clients. And they intend to verify this claim at
99\% confidence. H0: mean = 7.6 minutes H1: mean != 7.6 minutes

\hypertarget{iii.-estimate-the-population-mean-and-the-99-confidence-interval-ci-of-this-estimate}{%
\subsubsection{iii. Estimate the population mean, and the 99\%
confidence interval (CI) of this
estimate}\label{iii.-estimate-the-population-mean-and-the-99-confidence-interval-ci-of-this-estimate}}

population mean

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}\OtherTok{\textless{}{-}}\FunctionTok{mean}\NormalTok{(raw) }\CommentTok{\#sample mean}
\NormalTok{SE}\OtherTok{\textless{}{-}}\FunctionTok{sd}\NormalTok{(raw)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{length}\NormalTok{(raw)) }\CommentTok{\#standard\_error}
\NormalTok{CI}\FloatTok{.99} \OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(x}\FloatTok{{-}2.58}\SpecialCharTok{*}\NormalTok{SE , x}\FloatTok{+2.58}\SpecialCharTok{*}\NormalTok{SE)}

\CommentTok{\# Estimate the population mean}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"Estimate the population mean: \%f"}\NormalTok{, x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Estimate the population mean: 8.522009"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Because sample mean is the unbiased estimator of population\textquotesingle{}s, x is the estimation of population mean,}

\CommentTok{\#99\% confidence interval}
\NormalTok{CI}\FloatTok{.99} 
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.593073 9.450946
\end{verbatim}

As the markdown above, the 99\% confidence interval is {[}7.593073 ,
9.450946 {]}. And the Estimate the population mean is 8.522009

\hypertarget{iv.-using-the-traditional-statistical-testing-methods-we-saw-in-class}{%
\subsubsection{iv. Using the traditional statistical testing methods we
saw in
class,}\label{iv.-using-the-traditional-statistical-testing-methods-we-saw-in-class}}

find the t-statistic and p-value of the test

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Let 7.6 = μ0}
\NormalTok{manager\_hyp }\OtherTok{\textless{}{-}} \FloatTok{7.6}

\NormalTok{SE }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(raw)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{length}\NormalTok{(raw)) }\CommentTok{\#standard\_error}
\NormalTok{t  }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{mean}\NormalTok{(time)}\SpecialCharTok{{-}}\NormalTok{manager\_hyp)}\SpecialCharTok{/}\NormalTok{SE}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in mean.default(time): 引數不是數值也不是邏輯值：回覆 NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t }\CommentTok{\# t statistic}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#caculation p{-}value of the test t}
\NormalTok{df}\OtherTok{=}\FunctionTok{length}\NormalTok{(raw)}\SpecialCharTok{{-}}\DecValTok{1} \CommentTok{\#degree of freedom{-}1 to get unbiaed estimator}
\NormalTok{p\_value}\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pt}\NormalTok{(t,df)}
\NormalTok{p\_value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA
\end{verbatim}

Ans: t-value = 2.560762 p\_value = 0.005265342

\hypertarget{v.-briefly-describe-how-these-values-relate-to-the-null-distribution-of-t-not-graded}{%
\subsubsection{v. Briefly describe how these values relate to the Null
distribution of t (not
graded)}\label{v.-briefly-describe-how-these-values-relate-to-the-null-distribution-of-t-not-graded}}

Ans:

T-distributions assume that us draw repeated random samples from a
population where the null hypothesis is true. For t-value, as the sample
data become progressively dissimilar from the null hypothesis, the
absolute value of the t-value increases. And the p-value is the
probability under H0 of observing a test statistic at least as extreme
as what was observed.

\hypertarget{vi.-what-is-your-conclusion-about-the-advertising-claim-from-this-t-statistic-and-why}{%
\subsubsection{vi. What is your conclusion about the advertising claim
from this t-statistic, and
why?}\label{vi.-what-is-your-conclusion-about-the-advertising-claim-from-this-t-statistic-and-why}}

Conclusion: Fail to reject H0. Because, t-value = 2.560762 \& p\_value =
0.005265342 \textgreater0.005, And the hypothesized condition is
rejected if the p-value \textless{} 0.005 as 99\% confident level.

\hypertarget{b.-lets-use-bootstrapping-on-the-sample-data-to-examine-this-problem}{%
\subsection{b. Let's use bootstrapping on the sample data to examine
this
problem:}\label{b.-lets-use-bootstrapping-on-the-sample-data-to-examine-this-problem}}

\emph{Basic setting for question b first}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sample\_size \textless{}{-} length(raw)\# 1687}
\CommentTok{\# sample\_mean \textless{}{-} mean(raw) \# 8.522009}
\CommentTok{\# sample\_sd \textless{}{-} sd(raw) \# 14.78848}
\NormalTok{hypmanager\_hyp }\OtherTok{\textless{}{-}} \FloatTok{7.6}
\NormalTok{num\_boots }\OtherTok{\textless{}{-}} \DecValTok{2000}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\tightlist
\item
  Bootstrapped Percentile: Estimate the bootstrapped 99\% CI of the mean
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{53151}\NormalTok{)}
\NormalTok{Simple\_boost }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(func, sample0) \{}
\NormalTok{  resample }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(sample0, }\FunctionTok{length}\NormalTok{(sample0), }\AttributeTok{replace=}\ConstantTok{TRUE}\NormalTok{)}
  \FunctionTok{func}\NormalTok{(resample) }
\NormalTok{  \}}

\NormalTok{sample\_means }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(num\_boots, }\FunctionTok{Simple\_boost}\NormalTok{(mean, raw)) }

\CommentTok{\# plot(density(sample\_means), lwd=2, main="The Bootstrapped 99\% CI of the mean") }

\NormalTok{BootCI99 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(sample\_means, }\AttributeTok{probs =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.005}\NormalTok{, }\FloatTok{0.995}\NormalTok{))}
\NormalTok{BootCI99 }\CommentTok{\# 99\% CI interval}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     0.5%    99.5% 
## 7.662153 9.568937
\end{verbatim}

\hypertarget{ii.-bootstrapped-difference-of-means}{%
\subsection{ii. Bootstrapped Difference of
Means:}\label{ii.-bootstrapped-difference-of-means}}

What is the 99\% CI of the bootstrapped difference between the
population mean and the hypothesized mean?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Bootstrapping the 95\% CI of the Difference of Means}
\CommentTok{\# I paste the code from the pdf}
\NormalTok{boot\_mean\_diffs }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(sample0, mean\_hyp) \{}
\NormalTok{resample }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(sample0, }\FunctionTok{length}\NormalTok{(sample0), }\AttributeTok{replace=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{return}\NormalTok{( }\FunctionTok{mean}\NormalTok{(resample) }\SpecialCharTok{{-}}\NormalTok{ mean\_hyp )}
\NormalTok{\}}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{64264}\NormalTok{)}
\NormalTok{num\_boots }\OtherTok{\textless{}{-}} \DecValTok{2000}
\NormalTok{mean\_diffs }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(}
\NormalTok{num\_boots,}
\FunctionTok{boot\_mean\_diffs}\NormalTok{(raw, manager\_hyp)}
\NormalTok{)}
\NormalTok{diff\_ci\_99 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(mean\_diffs, }\AttributeTok{probs=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.005}\NormalTok{, }\FloatTok{0.995}\NormalTok{))}
\NormalTok{diff\_ci\_99}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       0.5%      99.5% 
## 0.02777012 1.83839069
\end{verbatim}

Ans: The 99\% CI of the bootstrapped mean difference is {[}0.02777012 ,
1.83839069 {]} under my seed setting as 64264.

\hypertarget{iii.-bootstrapped-t-interval}{%
\subsection{iii. Bootstrapped
t-Interval:}\label{iii.-bootstrapped-t-interval}}

\hypertarget{what-is-99-ci-of-the-bootstrapped-t-statistic}{%
\subsubsection{What is 99\% CI of the bootstrapped
t-statistic?}\label{what-is-99-ci-of-the-bootstrapped-t-statistic}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# i pasted the code fro the slides}
\NormalTok{boot\_t\_stat }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(sample0, mean\_hyp) \{}
\NormalTok{resample }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(sample0, }\FunctionTok{length}\NormalTok{(sample0), }\AttributeTok{replace=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{diff }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(resample) }\SpecialCharTok{{-}}\NormalTok{ mean\_hyp}
\NormalTok{se }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(resample)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{length}\NormalTok{(resample))}
\FunctionTok{return}\NormalTok{( diff }\SpecialCharTok{/}\NormalTok{ se )}
\NormalTok{\}}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2346786}\NormalTok{)}
\NormalTok{num\_boots }\OtherTok{\textless{}{-}} \DecValTok{2000}
\NormalTok{t\_boots }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(num\_boots, }\FunctionTok{boot\_t\_stat}\NormalTok{(raw, manager\_hyp))}
\CommentTok{\# plot(density(t\_boots), xlim=c(0,12), col="blue", lwd=2)}

\NormalTok{t\_ci\_99 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(t\_boots, }\AttributeTok{probs=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.005}\NormalTok{, }\FloatTok{0.995}\NormalTok{))}
\NormalTok{t\_ci\_99}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      0.5%     99.5% 
## 0.2434266 4.6637516
\end{verbatim}

Ans: the 99\% CI of the bootstrapped t-statistic is {[}0.2434266 ,
4.6637516 {]} under my seed setting as 2346786.

\hypertarget{iv.-plot-separate-distributions-of-all-three-bootstraps-above}{%
\subsection{iv. Plot separate distributions of all three bootstraps
above}\label{iv.-plot-separate-distributions-of-all-three-bootstraps-above}}

(for ii and iii make sure to include zero on the x-axis)

\hypertarget{iv}{%
\subsubsection{iv}\label{iv}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{1}\NormalTok{)) }

\NormalTok{pop\_the\_sh\_out }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(boost\_data, ci, title) \{}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(boost\_data),}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{main =}\NormalTok{ title)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{v=}\NormalTok{ci, }\AttributeTok{lty=}\DecValTok{1}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{1}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\NormalTok{\}}


\FunctionTok{pop\_the\_sh\_out}\NormalTok{(sample\_means,BootCI99, }\StringTok{"Distribution of sample\_means"}\NormalTok{ )}

\FunctionTok{pop\_the\_sh\_out}\NormalTok{(mean\_diffs,diff\_ci\_99, }\StringTok{"Distribution of mean\_diffs"}\NormalTok{ )}

\FunctionTok{pop\_the\_sh\_out}\NormalTok{(t\_boots,t\_ci\_99, }\StringTok{"Distribution of t\_boots"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW4_files/figure-latex/unnamed-chunk-11-1.pdf}
\#Explain: As the plot shown above, the red vertical lines are the 99\%
CI of each plot.

\hypertarget{c.-do-the-four-methods-traditional-test-bootstrapped-percentile-bootstrapped-difference-of-means-bootstrapped-t-interval-agree-with-each-other-on-the-test}{%
\subsection{c.~Do the four methods (traditional test, bootstrapped
percentile, bootstrapped difference of means, bootstrapped t-Interval)
agree with each other on the
test?}\label{c.-do-the-four-methods-traditional-test-bootstrapped-percentile-bootstrapped-difference-of-means-bootstrapped-t-interval-agree-with-each-other-on-the-test}}

Ans. \emph{Kindly notice that all of my STATEMENTS are answered under my
seed setting.} For this question, I will do the calculation separately,
then, summarize afterward.

\begin{itemize}
\tightlist
\item
  \emph{For traditional test}, Because, t-value = 2.560762 \& p\_value =
  0.005265342 \textgreater{} 0.005, And the hypothesized condition is
  rejected if the p-value \textless{} 0.005 as 99\% confident
  level(Two-tails). Therefore, we can not reject H0.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"For traditional test"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "For traditional test"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"t: \%f"}\NormalTok{,t)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "t: NA"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"p\_value: \%f"}\NormalTok{,p\_value)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "p_value: NA"
\end{verbatim}

\emph{For bootstrapped percentile}, the hypothesis mean (7.6) is not
includes in 99\% C.I range{[}7.662153 ,9.568937{]}. Therefore, we reject
H0.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"For bootstrapped percentile"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "For bootstrapped percentile"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(BootCI99)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     0.5%    99.5% 
## 7.662153 9.568937
\end{verbatim}

\emph{For bootstrapped difference of means } As the plot shown in IV,
the 0 is not includes in the 99\% range {[}0.02777012 ,1.83839069 {]}
Therefore, we reject H0.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"bootstrapped difference of means"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "bootstrapped difference of means"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(diff\_ci\_99)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       0.5%      99.5% 
## 0.02777012 1.83839069
\end{verbatim}

\emph{For the T interval }

As the plot shown in IV, the 0 is not includes in the 99\% range
{[}0.02777012 ,1.83839069{]} Therefore, we reject H0.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"t interval"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "t interval"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(t\_ci\_99)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      0.5%     99.5% 
## 0.2434266 4.6637516
\end{verbatim}

However, because of the random seed, the outcome will be different
sometime, as the lower bounds are very close to 7.6 and 0 in this case,
so it will sometime accept the H0 because of the random seed.

\emph{Summary} According to the calculation and the detailed explanation
mentioned above, we could not reject H0 base on traditional test.
However, we could reject H0 based on the rest of method. Hence, they are
not agree with each other. Lastly,I wished to stress again that the
`seed' would affect the result. Therefore, my answer only valid under
the current setting of seed.

\end{document}
